name: 🐞 Issue
description: File a issue
title: "Bug, File issue"
labels: ["Issue", "Good First Issue"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Tell me about the issue, what happens when you try to [...]?
    description: | A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected behavior of issue
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Make a pullrequest if you want to collab and have a solution or any other thoughts put them here!
    description: Any other thoughts!
  validations:
    required: false
